### ISSUE TITLE
Bug? .toXml(); / No ele data

### ISSUE THREAD

**Issue by johnjore** [MichaelFCoyle/SharpGPX#7]
Hi!

Not sure if this is a bug, or a "feature"?

I sample / save a GPS position every few seconds to something like this:
track.Tracks[0].trkseg[0].trkpt[0..7]
I have 8 of these, and all have the field "ele" populated with actual numbers

I use GPX = track.ToXml()

GPX:
`"<?xml version=\"1.0\" encoding=\"utf-16\"?>\n<gpx xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" version=\"1.1\" xmlns=\"http://www.topografix.com/GPX/1/1\">\n  <metadata>\n    <name>01/03/2022 20:03</name>\n    <desc>Description</desc>\n    <author>\n      <name>Something</name>\n    </author>\n    <bounds minlat=\"0\" minlon=\"0\" maxlat=\"0\" maxlon=\"0\" />\n  </metadata>\n  <trk>\n    <name>01/03/2022 20:03</name>\n    <trkseg>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:00:21.757776+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:00:26.731947+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:00:31.736753+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:00:36.737293+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:02:59.958214+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:03:03.512607+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:03:03.530771+11:00</time>\n      </trkpt>\n      <trkpt lat=\"0\" lon=\"0\">\n        <time>2022-03-01T20:03:04.95386+11:00</time>\n      </trkpt>\n    </trkseg>\n  </trk>\n</gpx>"`

Note that I have fudged the lat/lon fields, and can be ignored.

Why no elevation data? (ele) ?

**Comment by MichaelFCoyle** [comment]
Depending on how you set the elevation value this is "expected" behaviour. 
Let me explain.

The "ele" field has a corresponding "eleSpecified" field to indicate whether it's been set to a valid number. This is important because in the underlying xml the "ele" field is declared as optional, and this is how the serialization system decides whether to "write" it. 

It's optional because there may not be a valid elevation value, and specifying "0" or some other value in this field as a default could lead to someone interpreting the data as being valid when it is default. So "eleSpecified" 

There's also a "timeSpecified" and you will find "Specified" fields all over the api.

If you build a wpt class using the constructor, everything works automatically because the "elevation" field in the constructor is nullable. Looking at the code, you can see the constructor checks "hasValue" for elevation and time, and sets the appropriate "Specified" fields.

If you set the fields "by hand" or in an object initializer, this doesn't happen and you also need to manually set the corresponding "Specified" field.

**All that being said**, I do not like how cumbersome and prone to error this is and am looking for a better solution. In the wpt class there is a "Preserialize" method that gets called just before the class is serialized to XML. I propose to add some code to this class to do some simple checking so this doesn't happen with the Time field. I could set the "ele" field to decimal.MaxValue on construction and check whether it has been changed on serialization and and automatically set the "eleSpecified" field.

Until then you can work around this behaviour by using the constructor or manually setting "eleSpecified"

**Comment by johnjore** [comment]
Thanks for the explanation!

**Comment by MichaelFCoyle** [comment]
thanks for testing. I committed code to resolve the issue as described and am uploading a new release today.
